### ISSUE TITLE
KeePass-Reference support

### ISSUE THREAD

**Issue by tjarksaul** [jameshurst/KeePassHttp-ObjC#1]
It seems like [KeePass References](http://keepass.info/help/base/fieldrefs.html) are not supported with this plugin. ChromeIPass just shows the {REF:U@... string when I select an entry with references. Could you look into this?

**Comment by jameshurst** [comment]
Resolved in https://github.com/jamesrhurst/MacPass/commit/fd4c13b3d1456eadbf4f01403590a077b96c4f3f.
